server:
  port : 7777
  servlet:
    context-path: /api

spring:
  profiles:
    active: local

---
# 개발
spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:3306/booxby?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# 배포 환경
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/booxby2?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver