server:
  port : 7777
  servlet:
    context-path: /api

spring:
  profiles:
    active: local

  mail:
    host: smtp.gmail.com
    port: 587
    username: booxby21@gmail.com
    password: booxbyssafy2021
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---
# 개발
spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:3306/booxby?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# 배포 환경
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://j5b203.p.ssafy.io:3306/booxby?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: ssafybooxby
    driver-class-name: com.mysql.cj.jdbc.Driver
